### ISSUE TITLE
Tracking Issue for Milestone 3.0: "Algonac"

### ISSUE THREAD

**Issue by nhubbard** [nhubbard/librecampus#2]
This issue is for tracking the progress of release 3.0 of Librecampus ("Algonac"). I will be (again) completely rewriting the application to improve the usage of the product.
Here is the list of priorities:

- [ ] Rewrite the authenticator to allow for token-based authentication (sign in with one class, use the tokens on another).
- [ ] Replace the factory model with something more natural to work with, probably using RxPython.
- [ ] Replace the types with `attrs`, as I don't even have Python 3.7 yet. Writing classes manually is hard.

These will take a *long* time to build, so the project will not be ready for a while.
